### PR TITLE
[license] adjust year of creation

### PR DESCRIPTION
**Pull request by dglaeser**

### CODE REVIEW

**Comment by dglaeser** [comment]
@timokoch, I changed the license headers. As far as I know the year should simply be the year of creation. I think I copied this style from somewhere... the script in the `util` folder is actually obsolete, I think. The `reuse` helper scripts should deal with this, but I think when I introduced it it couldn't make it work so I added that script. We could just delete it, but I thought it also doesn't really hurt to keep it...

**Comment by timokoch** [comment]
I don't think this matters. Creation date should be fine, creation + any modification dates also. Without year is also fine. So I think the current state seems fine. Everything is tracked by git so the dates are not really needed. Haven't many of these been created in 2022?

**Comment by dglaeser** [comment]
yes it's probably not so important, because `reuse lint` does not complain... I just thought it would be cleaner for it not to look like "copyright from - to" (although it's legally irrelevant, probably). Yeah some of them are from (end of 2022), I had copied stuff from another git repo where I originally started developing this in the beginning of 22. But in this repo, most of the stuff is from 2023.

**Comment by timokoch** [comment]
Close this?

**Pull request closed without merging**
