### PR TITLE
Feature/small doxygen fixes

### PR DESCRIPTION
**Pull request by timokoch**
The newer doxygen fixes an issue with the sidebar width.
The encoder addtogroup didn't work somehow so I'm using manual ingroups.

### CODE REVIEW

**Comment by dglaeser** [comment]
what went wrong with the ingroup? On `main` (with the older doxygen version), this seems to work: https://dglaeser.github.io/gridformat/group__Encoding.html?

All classes appear in the Encoding module.

**Comment by timokoch** [comment]
The classes appear but the variables don’t

**Comment by dglaeser** [comment]
Ah, interesting... For the api I think it worked, there is also used the addtogroup cmd (see `gridformat.hpp`. I think the variables needed a doxygen brief, though, to appear. Or am I missing something again?

**Comment by timokoch** [comment]
I though `//!<` is equivalent to brief and the variables had that. I can try wrapping in a section again and not repeat the ingroup.

**Comment by timokoch** [comment]
mm ok but in `gridformat.hpp` the variables are all in one block whereas here it's one variable per file.

**Comment by timokoch** [comment]
@dglaeser how do you like the updated version? The addtogroup somehow didn't work when namespaces are switched. So I needed to add it twice. I also think with nested namespaces it's easier to read what is in which (sub)namespace but that's subjective. I can change it back.

**Comment by dglaeser** [comment]
cool, thank you! I think it's nice to read like this.. just so that I get it right, a working alternative would have been:

```cpp
namespace GridFormat {
//! \addtogroup Encoding
//! \{

...

//! \} group Encoding
namespace Encoding {
//! \addtogroup Encoding

...

//! \} group Encoding
} // namespace Encoding
}  // namespace GridFormat
```

?

**Comment by timokoch** [comment]
yes, that also worked.

**Comment by timokoch** [comment]
I started the [action](https://github.com/timokoch/gridformat/actions/runs/5412337486/jobs/9836299910) but of course I don't have rights to push the image.

**Comment by dglaeser** [comment]
ok, so I suggest I now trigger the image rebuilding action with this branch s.t. the new doxygen version is installed in them. This way we test the changes to the dockerfile. If that passes I'd merge and then we see the result in the deployed docu

**Comment by dglaeser** [comment]
ok and I don't have admin rights to your repo to start the action :). let's just merge once the WF is through, and then I retrigger. The images only get updated if the action passes, so in case something went wrong we can fix the dockerfile in a PR in my repo before pushing the new images. ok?

**Pull request merged**
