### PR TITLE
LagrangeMesh -> LagrangePolynomialGrid

### PR DESCRIPTION
**Pull request by dglaeser**

### CODE REVIEW

**Comment by dglaeser** [comment]
@timokoch, what do you think? I wanted to avoid different terms (i.e. `mesh` and `grid`). I wanted to stick to one term, that is `grid`, which is used throughout the library. But, I am unsure about this class name in general, do you think it's fine or is this unintuitive?

**Comment by timokoch** [comment]
maybe CurvedGeometryGrid? Lagrange doesn’t make me immediately think about Langrange polynomial bases in the context of grid.

**Comment by dglaeser** [comment]
Sounds good, thanks! I'll change it in this PR

**Comment by dglaeser** [comment]
I just came across this again. How about simply `HigherOrderGrid` then? This (as well as `CurvedGeometryGrid`) doesn't make it explicit that it is using lagrange polynomials, however, I don't see an immediate risk that we'll implement other forms of higher-order grids any time soon. If this ever happens we could still think of a new name, or some specializations on the type of basis etc...

**Comment by timokoch** [comment]
HigherOrderPolynomialGrid? higher order alone doesnt mean much

**Comment by dglaeser** [comment]
But then it still doesn't make it explicit which type of polynomials... I Like `Polynomial`, though, what if we do `LagrangePolynomialGrid`? It actually also works with order 1, so it's not necessarily higher-order...

**Comment by timokoch** [comment]
looks good, can you update the MR title?

**Pull request merged**
